sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: '8'
install: npm install
script:
  - npm install codecov -g
  - npm run build
  - npm run validate
after_script: "cat ./coverage/lcov.info | $(npm bin)/codecov"
after_success:
  - codecov
branches:
  only:
  - master