sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: '8'
install: npm install
script:
  - npm run validate
  - npm run coverage
after_script: "cat ./coverage/lcov.info | $(npm bin)/codecov"
branches:
  only:
  - master